### ISSUE TITLE
Bug regarding holidays

### ISSUE THREAD

**Issue by Mopade** [janzzon/difftimeOffice#4] opened 2020-06-02 12:52 UTC
Hello John, 

First thank you very much for your function "difftimeOffice" which is so great, I use it all the time! :) 

Unfortunately, I'm posting this issue because I think I found a bug regarding holidays :-/

I never used before the holidays parameter, it is the first time. 

One example of your function that I use in my script (I reduced the numbers of holidays for my example to be more readable): 

"difftime_office_hours(Start_date, Creation_date, holidays = c('05/01/2020', '05/08/2020', '05/21/2020'), working_hours = c(8, 18))/60))"

And one example with data in a row wich doesn't work fine : 
Start_date
05/01/2020  10:00:00 <== holiday

(05/02 and 05/03 are the week-end)

Creation_date
05/05/2020  08:59:00

The result of the function : 
Time_Creation_R
-61

=> As you can see, the result is -61. 
I saw this bug in every row where the holiday (here 01/05/2020) start in a hour "after" the hour of the 2nd day (here Creation_date = "05/05/2020"). 

For example this one works fine : 
Start_date
01/05/2020 09:00

Creation_date
04/05/2020 09:06

The result of the function : 
Time_Creation_R
6

Thank you very much for your help :-) 

Mopade

**Comment by johncassil** [comment] 2020-06-02 16:53
Mopade,

Good to hear you are getting value out of the package!  @janzzon built it.  I just helped with holidays.  

I'm had a bit of trouble understanding your examples, and what the problem is. 

You are referencing _Time_Creation_R_ but I don't know what's in that function.  You may be building on top of this function introduced some additional complexity that I can't see or help with.

After reviewing, it looks like the difftime_office_hours function is adding work hours that come from the first and last day, regardless of the holidays.  This seems to be an oversight on my part, but may be structural to the way these functions are designed.  I will have to dig further.

Please check the following example for a reproducible example:

```
library(dplyr)
library(lubridate)
library(difftimeOffice)
start_time <- lubridate::mdy_hm('05/01/2020 04:06') #May 1st, 2020 at 4am
end_time <- lubridate::mdy_hm('05/01/2020 09:00') #May 1st, 2020 at 9am

difftimeOffice::difftime_office_hours(start_time, 
                                      end_time, 
                                      holidays = c('05/01/2020'),
                                      working_hours = c(8, 18))

#Should give back 0 hours because May 1st is a holiday, but instead it gives back "32400s (~9 hours)" (I'm trying to figure out why.)
```

**Comment by Mopade** [comment] 2020-06-02 17:40
Thank you for your help John :) 

"Time_Creation_R" in my script is the result of your function difftime_office_hours, I put the result in it. 
And I forgot to say that my results are expressed in minutes, because I divide the result of your function by 60 to have the result expressed in minutes. 

I have tried the example that you show, same problem for me.

**Comment by johncassil** [comment] 2020-06-02 20:51
Mopade,

I think I fixed this issue.  I also fixed another bug, which was that the function wouldn't give back proper times if the starting and ending times were on the same date.  

You can wait until @janzzon approves the pull request, or you can go ahead and try it by installing it from the pull request with 
`devtools::install_github("janzzon/difftimeOffice#5")`

**Comment by Mopade** [comment] 2020-06-03 09:30
Hello John, 

Thank you very much for your help. 
I've tried your update, unfortunately it seems to fix the bug but to add others :-(

2 examples  : 

1) 
First date               | Second date
05/01/2020 10:00 | 05/04/2020 08:59
=> Works fine now. As previously said, I divide the result by 60 and find 58 minutes. 

2) 
First date               | Second date
05/04/2020 09:10 | 05/04/2020 09:18
=> Was working before, and now is not working. This day in France is a normal day, it is not holiday.
=> The result before your modifications and fixes was 8 minutes (make sense). 
=> Now the result is -600 :-( (As previously said I always divide the result by 60)

**Comment by Mopade** [comment] 2020-06-03 10:21
Yes, unfortunately I can confirm that with your fix I can see a lot of new errors with result -600 (I always divide the result by 60).

**Comment by Mopade** [comment] 2020-06-03 10:23
I'm available by IM or skype/discord if you need :-) 
And thank you again a lot for your help.

**Comment by johncassil** [comment] 2020-06-03 14:07
Hello Mopade.  

Thanks for testing!

I'm not certain that I can reproduce anything like this.  I have several tests on my side and they are all working.  In fact, the examples you gave above work too.  I would need more examples. 

Please run the following code to remove and reinstall package:

```
remove.packages('difftimeOffice')
devtools::install_github("janzzon/difftimeOffice#5")

```
Then Restart R (CTRL SHIFT F10 on a PC), and run these examples (they contain your times above):

```library(dplyr)
library(lubridate)
library(difftimeOffice)


start_time <- lubridate::mdy_hm('05/01/2020 10:00')
end_time <- lubridate::mdy_hm('05/04/2020 08:59')
difftimeOffice:::difftime_office_hours(start_time, 
                                       end_time, 
                                       holidays = c('05/01/2020', '05/08/2020', '05/21/2020'),
                                       working_hours = c(8, 18))

# provides expected value of: "3540s (~59 minutes)"

start_time <- lubridate::mdy_hm('05/04/2020 09:10')
end_time <- lubridate::mdy_hm('05/04/2020 09:18')
difftimeOffice:::difftime_office_hours(start_time, 
                                       end_time, 
                                       holidays = c('05/01/2020', '05/08/2020', '05/21/2020'),
                                       working_hours = c(8, 18))

# provides expected value of: "480s (~8 minutes)"
```
If it still doesn't work, I don't really have an answer.  I am running 3.4.2, dplyr 0.8.3 and lubridate 1.7.4

**Comment by Mopade** [comment] 2020-06-03 17:09
I find the same results than you with the examples that you show :-/ 
I've tried to figure why my problem on another context is not working. 
I've spent 3 hours, I don't find why, all was working normally (except holidays) before your modification. 
So to show you the problem I've made a GIF I think that the best way to show you :) 
Here it is :

**Comment by johncassil** [comment] 2020-06-03 17:50
Mopade, 
I'm sorry you're not having luck.  

If it helps for the short term, you can uninstall and reinstall the old version with this:
```
remove.packages('difftimeOffice')
devtools::install_github("janzzon/difftimeOffice")
```

Would you do you mind sending me that spreadsheet in the gif?   I'm curious if I can reproduce anything over here.

**Comment by Mopade** [comment] 2020-06-03 18:03
Yes of course, here you can find the files (.xlsx and .Rmd) zipped : 
Thanks again John :-)

**Comment by johncassil** [comment] 2020-06-03 18:25
Mopade,

I'm not sure how much you know about the internals of how mutate works, but I believe it's best to use `rowwise` in your case, because otherwise, your function doesn't seem to be comparing each row's Date1 to each row's Date2. 

In addition, I think you had Date1 and Date2 switched.  I switched them back and used rowwise and I'm getting correct results for everything.  Try this for your second code chunk:
```{r message=FALSE,echo=FALSE}
  #calcul du temps entre la date d alerte et la date de création du ticket
all_tickets_with_time <- all_tickets %>% 
  rowwise() %>% 
  mutate(business_minutes_from_date1_to_date2 = difftime_office_hours(Date1, Date2, working_hours = c(8, 18))/60)

```
![image](https://user-images.githubusercontent.com/1057388/83674758-12653c00-a5a6-11ea-8bf1-b945c61a4384.png)

**Comment by Mopade** [comment] 2020-06-03 19:06
Seems to be way better. 

Thank you so much!! :-) 

I test again tomorrow and confirm you if all is fine now.

**Comment by Mopade** [comment] 2020-06-04 10:41
Hello again John. 

I've spent all the morning to check if all is fine. 

Found a new problem and this time I'm pretty sure of it :-/ 

Can you try : 

"""
library(lubridate)
library(difftimeOffice)

start_time <- lubridate::mdy_hm('05/17/2020 12:15')
end_time <- lubridate::mdy_hm('05/18/2020 08:01')
difftimeOffice:::difftime_office_hours(start_time, 
                                       end_time, 
                                       holidays = c('05/01/2020', '05/08/2020', '05/21/2020'),
                                       working_hours = c(8, 18))
"""
05/17/2020 is a sunday, so the result should give 60 seconds. 

The result give me : [1] "36060s (~10.02 hours)"  :-(

**Comment by johncassil** [comment] 2020-06-04 14:23
Thank you!

I don't use this function in my day to day, so I haven't had a lot of examples to test with, along with their expected values.  If you end up having a sheet, it might be helpful to save here in case we ever need it again.

I found my bug and updated the code to replace one variable with another and that should fix it.  You will have to uninstall and reinstall (from the same pull request[this time with different code])

```
remove.packages('difftimeOffice')
devtools::install_github("janzzon/difftimeOffice#5")

```

**Comment by Mopade** [comment] 2020-06-04 15:05
Thank you so much again John! :-) 
I know I say that a lot but everything seems to work completely fine now. It's so great. 
I've checked at lof of examples and all seems perfect!

**Comment by Mopade** [comment] 2020-09-15 13:42
Hello! 

Is the last update "difftimeOffice#5" applied now to be installed directly by using the following command ?

devtools::install_github("janzzon/difftimeOffice") 

Thanks!

**Comment by johncassil** [comment] 2020-09-15 14:59
Hi Mopade!

I'm not sure to what extent @janzzon is still updating this package or if he has time to merge the pull request & close these issues.  (Open source package maintainers don't get paid to do this. :) ) I added the patch to my copy of this repo which is available at https://github.com/johncassil/difftimeOffice/

I believe the most up to date package can be installed with `remotes::install_github("johncassil/difftimeOffice")`

**Comment by Mopade** [comment] 2020-09-15 16:36
OK, great, thank you John :-)

**Comment by janzzon** [comment] 2020-09-15 20:12
Sry for late reply @johncassil and @Mopade . Merged PR now.

**Closed as completed by janzzon** 2020-09-15 20:12 UTC
